--ignore Neurocast_Tools/elevenlabs_tool.lua
--ignore Neurocast_Tools/elevenlabs_manager_tool.lua
--ignore Neurocast_Tools/docx_import_tool.lua
--ignore Neurocast_Tools/neurocast_script_aligner_tool.lua
--ignore Neurocast_Tools/mvsep_tool.lua
--ignore Neurocast_Tools/actions-neurocast/
--ignore Neurocast_Tools/utilities-neurocast/
--ignore Neurocast_Tools/modules-neurocast/
--ignore Neurocast_Tools/licenses/curl-COPYING.txt
--ignore Neurocast_Tools/licenses/zlib-LICENSE.txt
--ignore Neurocast_Tools/licenses/7-Zip-License.txt
--ignore Neurocast_Tools/licenses/Unicode-License.txt
