-- Generated by python_helpers/generate_languages_lua.py
-- Generated at: 2026-06-11T17:48:17Z
-- Locale: ru
-- Inventory: C:/code/auphonic-mt/python_helpers/loc/neurocast_script_aligner_dev_main/inventory/source_inventory.json
-- Translator JSON: C:/code/auphonic-mt/python_helpers/loc/neurocast_script_aligner_dev_main/translator_output/translated_ru.json
-- Output: C:/code/auphonic-mt/scr/modules/neurocast_script_aligner_dev_main_languages.lua
-- Do not edit this file manually.

return {
  locale = "ru",
  translations_by_source_text = {
    ["Debug"] = "Отладка",
    ["Warnings"] = "Предупреждения",
    ["Info"] = "Информация",
    ["Errors"] = "Ошибки",
    ["Off"] = "Выкл.",
    ["Logging threshold"] = "Порог файлового журнала",
    ["Logging threshold save failed: %s"] = "Не удалось сохранить порог файлового журнала: %s",
    ["Messaging threshold"] = "Порог сообщений",
    ["Messaging threshold save failed: %s"] = "Не удалось сохранить порог сообщений: %s",
    ["Log folder: %s"] = "Папка журналов: %s",
    ["Current log file: %s"] = "Текущий файл журнала: %s",
    ["(created after the first matching message)"] = "(будет создан после первого подходящего сообщения)",
    ["Copy log folder"] = "Скопировать путь к папке журналов",
    ["Local logs may contain project paths, filenames, and workflow content."] = "Локальные журналы могут содержать пути проекта, имена файлов и содержимое рабочего процесса.",
    ["Messaging is Off. Util-driven errors may be hidden."] = "Вывод сообщений отключен. Ошибки от Util могут быть скрыты.",
    ["Settings"] = "Настройки",
    ["Account / Credentials"] = "Учетная запись / Учетные данные",
    ["Paths"] = "Пути",
    ["Diagnostics"] = "Диагностика",
    ["Telemetry"] = "Телеметрия",
  }
}
